# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a4e190467459cb79f6ca8616bf7ee34f2b835de11696eadd5c189bcb54343d18ae67368f6020cf2eda0c7fac63c01dbc08bb523b5ce3aba5855144c4f5f7078

test:
  secret_key_base: f8034bdc542fd68276c2891b3dd47a7f7a4e9af5c4a2eae9f5d1c2f927c447d55ef920c7b2ad746c0b222bc266085a06f4b4fb09dd6f3b5a5989be683bc86d61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
